//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QToolbar.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "14.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0, 0")]
        public global::System.Drawing.Point WindowLocation {
            get {
                return ((global::System.Drawing.Point)(this["WindowLocation"]));
            }
            set {
                this["WindowLocation"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("606, 132")]
        public global::System.Drawing.Size WindowSize {
            get {
                return ((global::System.Drawing.Size)(this["WindowSize"]));
            }
            set {
                this["WindowSize"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("X:\\Testing")]
        public string TestingFolder {
            get {
                return ((string)(this["TestingFolder"]));
            }
            set {
                this["TestingFolder"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("X:\\Toolkit Applications\\Designers")]
        public string DesignersFolder {
            get {
                return ((string)(this["DesignersFolder"]));
            }
            set {
                this["DesignersFolder"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("X:\\Testing\\QCS Admin")]
        public string QCSAdminFolder {
            get {
                return ((string)(this["QCSAdminFolder"]));
            }
            set {
                this["QCSAdminFolder"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("X:\\Testing\\QCS Agent")]
        public string QCSAgentFolder {
            get {
                return ((string)(this["QCSAgentFolder"]));
            }
            set {
                this["QCSAgentFolder"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("E:\\My\\Database Scripts")]
        public string SQLFolder {
            get {
                return ((string)(this["SQLFolder"]));
            }
            set {
                this["SQLFolder"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("X:\\Toolkit Applications\\ExecutorConfiguration")]
        public string ExecutorConfiguratorFolder {
            get {
                return ((string)(this["ExecutorConfiguratorFolder"]));
            }
            set {
                this["ExecutorConfiguratorFolder"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("X:\\Toolkit Applications\\Script Database")]
        public string DatabaseScripterFolder {
            get {
                return ((string)(this["DatabaseScripterFolder"]));
            }
            set {
                this["DatabaseScripterFolder"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("X:\\Toolkit Applications\\Field Explorer")]
        public string FieldsExplorerFolder {
            get {
                return ((string)(this["FieldsExplorerFolder"]));
            }
            set {
                this["FieldsExplorerFolder"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("<?xml version=\"1.0\" encoding=\"utf-16\"?>\r\n<ArrayOfString xmlns:xsi=\"http://www.w3." +
            "org/2001/XMLSchema-instance\" xmlns:xsd=\"http://www.w3.org/2001/XMLSchema\">\r\n  <s" +
            "tring>c:\\</string>\r\n</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection Folders {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["Folders"]));
            }
            set {
                this["Folders"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("X:\\Toolkit Applications\\Internal Deployment Tool\\Configuration")]
        public string EnvironmentsConfigurationFolder {
            get {
                return ((string)(this["EnvironmentsConfigurationFolder"]));
            }
            set {
                this["EnvironmentsConfigurationFolder"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Checkouts {
            get {
                return ((string)(this["Checkouts"]));
            }
            set {
                this["Checkouts"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("\\\\Q-SRV-INTTFSB\\InternalBuilds")]
        public string InternalBuildsFolder {
            get {
                return ((string)(this["InternalBuildsFolder"]));
            }
            set {
                this["InternalBuildsFolder"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string ShellCommands {
            get {
                return ((string)(this["ShellCommands"]));
            }
            set {
                this["ShellCommands"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"<DocumentElement>
  <table>
    <Name>v.6.11</Name>
    <Command>http://q-srv-w2k12r2:8804/QCLegalApplicationApp/</Command>
  </table>
  <table>
    <Name>v.7.2</Name>
    <Command>http://q-srv-w2k12r2:8807/QCLegalApplicationApp/</Command>
  </table>
  <table>
    <Name>v.7.3</Name>
    <Command>http://q-srv-w2k12r2:8800/QCLegalApplicationApp/</Command>
  </table>
</DocumentElement>")]
        public string LegalLinks {
            get {
                return ((string)(this["LegalLinks"]));
            }
            set {
                this["LegalLinks"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"<DocumentElement>
  <table>
    <Name>Flag 'ENABLE_EOD_MONITOR_AND_ALERTS'</Name>
    <SQL>SELECT * FROM AT_SYSTEM_PARAMS WHERE SPRA_TYPE='ENABLE_EOD_MONITOR_AND_ALERTS'</SQL>
    <RunImmediate>true</RunImmediate>
  </table>
  <table>
    <Name>Get Database Versions</Name>
    <SQL>SELECT * FROM TLK_DATABASE_VERSIONS ORDER BY 1 DESC</SQL>
    <RunImmediate>true</RunImmediate>
  </table>
  <table>
    <Name>Get Enterprises</Name>
    <SQL>select * from enterprises</SQL>
    <RunImmediate>true</RunImmediate>
  </table>
  <table>
    <Name>Get Installations</Name>
    <SQL>SELECT * FROM AT_INSTALLATIONS</SQL>
    <RunImmediate>true</RunImmediate>
  </table>
</DocumentElement>")]
        public string SQLQueries {
            get {
                return ((string)(this["SQLQueries"]));
            }
            set {
                this["SQLQueries"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ClearLegalMetadata {
            get {
                return ((bool)(this["ClearLegalMetadata"]));
            }
            set {
                this["ClearLegalMetadata"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"<DocumentElement>
  <table>
    <Repository>PROTEUS</Repository>
    <Path>QC.WebCollection.WebServices\qbc.cf</Path>
  </table>
  <table>
    <Repository>PROTEUS</Repository>
    <Path>QCS.BackOffice.WebServices\qbc.cf</Path>
  </table>
  <table>
    <Repository>PROTEUS</Repository>
    <Path>SCToolkit2.Designers.Client.WPF\qbc.cf</Path>
  </table>
  <table>
    <Repository>PROTEUS</Repository>
    <Path>SCToolkit2.Designers.WebServices\qbc.cf</Path>
  </table>
  <table>
    <Repository>PROTEUS</Repository>
    <Path>SCToolkit2.WebServices\qbc.cf</Path>
  </table>
  <table>
    <Repository>QC</Repository>
    <Path>VS Projects\CollectionAgentSystem\CollectionAgentSystemClient.BranchUI\qbc.cf</Path>
  </table>
  <table>
    <Repository>QC</Repository>
    <Path>VS Projects\CollectionAgentSystem\CollectionAgentSystemClient\qbc.cf</Path>
  </table>
  <table>
    <Repository>QC</Repository>
    <Path>VS Projects\QC.DataArchive\QC.DataArchive.Client\QC_DataArchive.cf</Path>
  </table>
  <table>
    <Repository>QC</Repository>
    <Path>VS Projects\QCS\MicroQCClient\qbc_admin.cf</Path>
  </table>
  <table>
    <Repository>QC</Repository>
    <Path>VS Projects\QCS\QCSClient\qbc_admin.cf</Path>
  </table>
  <table>
    <Repository>QC</Repository>
    <Path>VS Projects\QCS\QCSWS\qbc.cf</Path>
  </table>
  <table>
    <Repository>QC</Repository>
    <Path>VS Projects\SCToolkit\SCToolkitWS\qbc.cf</Path>
  </table>
</DocumentElement>")]
        public string EnvCFs {
            get {
                return ((string)(this["EnvCFs"]));
            }
            set {
                this["EnvCFs"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Q-SRV-SQL2K12")]
        public string QCWebServers {
            get {
                return ((string)(this["QCWebServers"]));
            }
            set {
                this["QCWebServers"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Q-SRV-DEVEL12,Q-SRV-DEVEL12\\MSSQL2K16")]
        public string DevSQLInstances {
            get {
                return ((string)(this["DevSQLInstances"]));
            }
            set {
                this["DevSQLInstances"] = value;
            }
        }
    }
}
